name: Copilot Setup Steps

on:
  workflow_call:

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Install .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Verify .NET version
        run: dotnet --info

      # Optional: restore any required tools or workloads
      - name: Restore tools
        run: dotnet tool restore
